CREATE TABLE rides (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    cab_id INT NOT NULL,
    start_point POINT NOT NULL,
    end_point POINT NOT NULL,
    time_start DATETIME NOT NULL,
    time_end DATETIME NOT NULL,
    fare DECIMAL(10, 2) NOT NULL,
    ride_time DECIMAL(10,2) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_cab FOREIGN KEY (cab_id) REFERENCES cabs(id) ON UPDATE CASCADE ON DELETE NO ACTION
);
